### ISSUE TITLE
Incorrect processing of string nodes

### ISSUE THREAD

**Issue by kubena** [caststack/python-mpd-parser#3]
Any string node results in "AttributeError: 'str' object has no attribute 'parse'".
Problem is in file utils.py(line 21): ``if isinstance(node_type, (str, unicode)):``
You are testing the type of variable node_type instead of testing the value. Line should be ``if node_type in (str, unicode):``

**Comment by onovy** [comment]
fixed in https://github.com/caststack/python-mpd-parser/pull/4

**Comment by sangwonl** [comment]
awesome, thanks!
